variable "name" {
  description = "Hetzner server name and default Tailscale hostname."
  type        = string
  default     = "devbox"

  validation {
    condition     = can(regex("^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}$", var.name))
    error_message = "name must be a DNS-safe hostname up to 63 characters."
  }
}

variable "username" {
  description = "Non-root sudo user created by cloud-init."
  type        = string
  default     = "myuser"

  validation {
    condition     = can(regex("^[a-z_][a-z0-9_-]{0,31}$", var.username))
    error_message = "username must be a valid Linux username."
  }
}

variable "ssh_public_key_path" {
  description = "Path to the SSH public key to install for root provisioning and the non-root user."
  type        = string
  default     = "~/.ssh/id_ed25519.pub"
}

variable "server_type" {
  description = "Hetzner server type, usually generated by scripts/choose-vm.py."
  type        = string
  default     = "cx23"
}

variable "location" {
  description = "Hetzner location code, usually generated by scripts/choose-vm.py."
  type        = string
  default     = "fsn1"
}

variable "image" {
  description = "Hetzner image slug."
  type        = string
  default     = "ubuntu-24.04"
}

variable "tailscale_auth_key" {
  description = "One-off or ephemeral Tailscale auth key. If empty, Tailscale is installed but not joined."
  type        = string
  default     = ""
  sensitive   = true
}

variable "dotfiles_repo_url" {
  description = "Optional Git repository cloned to /home/<username>/.dotfiles and bootstrapped on first boot. Leave empty until dotfiles are ready."
  type        = string
  default     = ""
}

variable "dotfiles_bootstrap_path" {
  description = "Path inside dotfiles_repo_url to execute as the user."
  type        = string
  default     = "bootstrap.sh"
}

variable "allow_public_ssh_cidrs" {
  description = "Temporary break-glass CIDRs allowed to SSH over the public interface. Keep empty for normal Tailscale-only access."
  type        = list(string)
  default     = []
}

variable "labels" {
  description = "Additional Hetzner labels."
  type        = map(string)
  default     = {}
}
